backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    path: '{{year}}-{{month}}-{{day}}--{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Featured Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'David Asaf' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    path: '{{title}}/index'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Menu Title', name: 'menuTitle', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
